# This file is used to configure redirects and other settings for Netlify.

# The [[redirects]] section is used to create a reverse proxy.
# This rule will proxy all requests from /odoo/* to your actual Odoo instance.
[[redirects]]
  # The path on your Netlify site that you will proxy from.
  # Do not change this unless you update the JS code in your index.html file.
  from = "/odoo/*"
  
  # The URL of your Odoo instance.
  # IMPORTANT: You MUST replace `your-odoo-instance.odoo.com` with the correct URL.
  to = "https://swarajr.odoo.com/:splat"
  
  # The status code must be 200 for a rewrite (proxy).
  status = 200
  
  # The force=true flag ensures that this rule is applied even if a file exists
  # at the same path on your site (e.g., if you had a folder named `/odoo`).
  force = true
